#!/bin/bash

# omarchy:summary=Remove the Hearth desktop integration (status bar item and menu)
# omarchy:args=[--bin-dir <dir>] [--purge]
# omarchy:examples=./uninstall.sh | ./uninstall.sh --purge

# Takes back exactly what install.sh added and nothing else. Your own bar
# widgets, your own menu entries and every backup it ever made are left alone.

set -euo pipefail

readonly source_dir="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
readonly config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
readonly conf_file="$config_home/hearth/omarchy.conf"
readonly stamp="$(date +%Y%m%d%H%M%S)"

bin_dir="$HOME/.local/bin"
purge=0

fail() {
  echo "${0##*/}: $*" >&2
  exit 1
}

note() { echo "  $*"; }

while (($# > 0)); do
  case "$1" in
    --bin-dir) bin_dir="${2:?--bin-dir needs a directory}"; shift 2 ;;
    --purge) purge=1; shift ;;
    -h | --help)
      cat <<USAGE
Usage: ./uninstall.sh [--bin-dir <dir>] [--purge]

  --bin-dir <dir>   where the commands were linked (default ~/.local/bin)
  --purge           also delete $conf_file
USAGE
      exit 0
      ;;
    *) fail "unknown option: $1" ;;
  esac
done

[[ $EUID -ne 0 ]] || fail "do not run this as root"

install_file() {
  local target="$1" new="$2"
  if [[ -f $target ]] && cmp -s "$new" "$target"; then
    return 1
  fi
  [[ ! -f $target ]] || cp -p "$target" "$target.hearth-backup-$stamp"
  cat "$new" >"$target"
  return 0
}

echo "Removing Hearth for Omarchy"
echo

# ------------------------------------------------------------------- menu

menu_file="$config_home/omarchy/extensions/omarchy-menu.jsonc"
begin_mark="// >>> hearth: generated by hearth-menu-jsonc, do not edit inside >>>"
end_mark="// <<< hearth <<<"

if [[ -f $menu_file ]] && grep -qF "$begin_mark" "$menu_file"; then
  tmp=$(mktemp)
  awk -v b="$begin_mark" -v e="$end_mark" '
    index($0, b) { skip = 1; next }
    skip && index($0, e) { skip = 0; next }
    skip { next }
    { print }
  ' "$menu_file" >"$tmp"
  if "$source_dir/bin/hearth-jsonc-check" "$tmp"; then
    install_file "$menu_file" "$tmp" && note "removed the Hearth entries from $menu_file" || true
  else
    note "leaving $menu_file alone: removing the block would not leave valid JSONC"
  fi
  rm -f "$tmp"
  omarchy-menu refresh >/dev/null 2>&1 || true
else
  note "no Hearth entries in $menu_file"
fi

# --------------------------------------------------------------------- bar

shell_json="$config_home/omarchy/shell.json"
if [[ -s $shell_json ]]; then
  tmp=$(mktemp)
  if jq -S '
      def entry_id: if type == "object" then (.id // "" | tostring) else tostring end;
      .bar.layout.left   = ((.bar.layout.left   // []) | map(select(entry_id != "hearth")))
      | .bar.layout.center = ((.bar.layout.center // []) | map(select(entry_id != "hearth")))
      | .bar.layout.right  = ((.bar.layout.right  // []) | map(select(entry_id != "hearth")))
    ' "$shell_json" >"$tmp" 2>/dev/null; then
    install_file "$shell_json" "$tmp" && note "removed the Hearth module from $shell_json" ||
      note "no Hearth module in $shell_json"
    omarchy-shell -q shell reloadConfig >/dev/null 2>&1 || true
  fi
  rm -f "$tmp"
fi

waybar_dir="$config_home/waybar"
for config in "$waybar_dir/config.jsonc" "$waybar_dir/config"; do
  [[ -f $config ]] || continue
  grep -q 'custom/hearth' "$config" || continue
  if grep -qE '^[[:space:]]*//' "$config"; then
    note "$config has comments in it, so it was left alone."
    note "Delete the \"custom/hearth\" module and its entry in modules-right."
    continue
  fi
  tmp=$(mktemp)
  if jq -S '
      del(."custom/hearth")
      | ."modules-left"   = ((."modules-left"   // []) | map(select(. != "custom/hearth")))
      | ."modules-center" = ((."modules-center" // []) | map(select(. != "custom/hearth")))
      | ."modules-right"  = ((."modules-right"  // []) | map(select(. != "custom/hearth")))
    ' "$config" >"$tmp" 2>/dev/null; then
    install_file "$config" "$tmp" && note "removed custom/hearth from $config" || true
    pkill -SIGUSR2 waybar 2>/dev/null || true
  fi
  rm -f "$tmp"
done

style="$waybar_dir/style.css"
if [[ -f $style ]] && grep -qF '/* >>> hearth >>> */' "$style"; then
  tmp=$(mktemp)
  awk '
    index($0, "/* >>> hearth >>> */") { skip = 1; next }
    skip && index($0, "/* <<< hearth <<< */") { skip = 0; next }
    skip { next }
    { print }
  ' "$style" >"$tmp"
  install_file "$style" "$tmp" && note "removed the Hearth styles from $style" || true
  rm -f "$tmp"
fi

# ---------------------------------------------------------------- commands

removed=0
for cmd in hearth-kidnet hearth-bar-status hearth-action hearth-menu-jsonc hearth-jsonc-check; do
  dest="$bin_dir/$cmd"
  if [[ -L $dest && "$(readlink -f "$dest")" == "$source_dir/bin/$cmd" ]]; then
    rm -f "$dest"
    removed=$((removed + 1))
  elif [[ -e $dest ]]; then
    note "left $dest alone: it is not a link to this checkout"
  fi
done
((removed == 0)) || note "removed $removed commands from $bin_dir"

rm -f "${XDG_RUNTIME_DIR:-/tmp}/hearth-bar-status.json"

# ------------------------------------------------------------------ config

if ((purge)); then
  rm -f "$conf_file"
  note "deleted $conf_file"
elif [[ -f $conf_file ]]; then
  note "kept $conf_file (use --purge to delete it)"
fi

echo
echo "Done. Backups of everything that changed are beside the originals,"
echo "named *.hearth-backup-*. Nothing on the gateway was touched."
